### ISSUE TITLE
Prevent over-scrolling of content

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-foundation-website#39]
**Is your feature request related to a problem? Please describe.**

Currently browser allow you to over-scroll, which reveals white space:
https://share.getcloudapp.com/Apujnkpm

**Describe the solution you'd like**

Prevent this ability, perhaps by:
https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior-y

**Describe alternatives you've considered**

**Additional context**

**Comment by JosefJ** [comment]
Hi, was this pushed to 'production'? 
I'm still seeing this behavior (latest Firefox/Brave) when hovering over the toggle footer button:

![EFPage_Scroll](https://user-images.githubusercontent.com/10713123/81474534-5f076280-9206-11ea-864a-979249c456d9.gif)

**Comment by samajammin** [comment]
Thanks @JosefJ - looking into this.

**Comment by samajammin** [comment]
@JosefJ this should now be fixed - please LMK & re-open this issue if you find anything still off.
