### ISSUE TITLE
Duplicated "what is EF?"

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-foundation-website#69]
**Describe the bug**
Not sure if this is a bug or not, just calling it out.

**To Reproduce**
1. Go to `/ethereum`
2. See duplicated "what is EF?" links in the content

**Expected behavior**
Maybe just have 1 of those 2 links?

**Screenshots**
![image](https://user-images.githubusercontent.com/468158/194169145-f2ffeb70-22fb-465b-9e79-5d844547e944.png)

**Comment by abdelshok** [comment]
This is not a duplicate, it was part of the initial designs that were shared with me.
